"""description_of_changes

Revision ID: 03cbf4864fd5
Revises: e2957278b5a5
Create Date: 2023-10-19 18:31:03.004756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03cbf4864fd5'
down_revision: Union[str, None] = 'e2957278b5a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'scene_prompts', ['title'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scene_prompts', type_='unique')
    # ### end Alembic commands ###
