"""description_of_changes

Revision ID: 361165c41ca2
Revises: 5853c4562fb4
Create Date: 2023-10-17 19:48:40.948004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '361165c41ca2'
down_revision: Union[str, None] = '5853c4562fb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scene_image_prompts', sa.Column('content', sa.Text(), nullable=False))
    op.drop_column('scene_image_prompts', 'prompt_content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scene_image_prompts', sa.Column('prompt_content', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('scene_image_prompts', 'content')
    # ### end Alembic commands ###
