"""description_of_changes

Revision ID: 5853c4562fb4
Revises: 8a2f42c897a2
Create Date: 2023-10-16 19:48:51.101292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5853c4562fb4'
down_revision: Union[str, None] = '8a2f42c897a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    op.drop_table('image_prompts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_prompts',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('image_prompts_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('scene_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('prompt_content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('dateadded', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('dateupdated', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], name='image_prompts_scene_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='image_prompts_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('images',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('prompt_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('image_path', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('dateadded', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('dateupdated', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['prompt_id'], ['image_prompts.id'], name='images_prompt_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='images_pkey')
    )
    # ### end Alembic commands ###
