"""description_of_changes

Revision ID: 8a2f42c897a2
Revises: e98fa8c55fdd
Create Date: 2023-10-15 06:56:47.287359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a2f42c897a2'
down_revision: Union[str, None] = 'e98fa8c55fdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenes', sa.Column('content', sa.Text(), nullable=False))
    op.drop_column('scenes', 'scene_content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenes', sa.Column('scene_content', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('scenes', 'content')
    # ### end Alembic commands ###
