"""description_of_changes

Revision ID: 8b228e17686f
Revises: cbca3ad416a7
Create Date: 2023-10-18 21:01:28.504365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b228e17686f'
down_revision: Union[str, None] = 'cbca3ad416a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scene_images', sa.Column('chunk_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'scene_images', 'chunks', ['chunk_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scene_images', type_='foreignkey')
    op.drop_column('scene_images', 'chunk_id')
    # ### end Alembic commands ###
