"""description_of_changes

Revision ID: cbca3ad416a7
Revises: 9fa4772494ef
Create Date: 2023-10-18 19:58:00.224873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbca3ad416a7'
down_revision: Union[str, None] = '9fa4772494ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scene_images', sa.Column('filename', sa.String(length=255), nullable=False))
    op.drop_column('scene_images', 'image_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scene_images', sa.Column('image_path', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('scene_images', 'filename')
    # ### end Alembic commands ###
