"""description_of_changes

Revision ID: e98fa8c55fdd
Revises: 0f9dcc0cd5b7
Create Date: 2023-10-15 02:19:06.684008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e98fa8c55fdd'
down_revision: Union[str, None] = '0f9dcc0cd5b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenes', sa.Column('title', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenes', 'title')
    # ### end Alembic commands ###
